red_box:
  lower:
  - 170
  - 100
  - 100
  lower2:
  - 0
  - 100
  - 100
  upper:
  - 180
  - 255
  - 255
  upper2:
  - 10
  - 255
  - 255
yellow_box:
  lower:
  - 19
  - 45
  - 90
  upper:
  - 60
  - 246
  - 255
