red_box:
  lower:
  - 170
  - 175
  - 104
  lower2:
  - 0
  - 140
  - 100
  upper:
  - 180
  - 255
  - 255
  upper2:
  - 10
  - 255
  - 255
yellow_box:
  lower:
  - 22
  - 73
  - 99
  upper:
  - 38
  - 255
  - 255

main_box:
  # White main box. It must contrast with the background.
  lower:
  - 0
  - 0
  - 170
  upper:
  - 180
  - 65
  - 255
  min_area: 2000
  min_frame_ratio: 0.02
  max_frame_ratio: 0.75
